apiVersion: v1
kind: Service
metadata:
  name: iperf-server
spec:
  selector:
    org: empire
    class: iperf-server
  ports:
    - protocol: TCP
      port: 5001
      targetPort: server
      name: server

---
apiVersion: v1
kind: Pod
metadata:
  name: iperf-client-pod
  labels:
    app.kubernetes.io/name: iperf-client
    org: alliance
    class: iperf-client
spec:
  containers:
    - name: iperf-client
      image: mlabbe/iperf
      command: ["/bin/sh", "-c", "sleep 1d"]
  terminationGracePeriodSeconds: 0
